export const mockData = [
  {
    name: "Hour of Intense Peace v2.3",
    type: "Yoga",
    start: "April 5th, 5:00 pm",
    duration: "1 hr",
    intensity: "High",
    location: "123 Elmo Street, Denver, Colorado",
    attendees: 4,
    maxsize: 20,
  },
  {
    name: "HIT Session 5.1",
    type: "Insanity",
    start: "April 6th, 5:30 pm",
    duration: "30 min",
    intensity: "High",
    location: "563 Meyers Street, Salt Lake City, Utah",
    attendees: 7,
    maxsize: 15,
  },
  {
    name: "Ab Nirvana",
    type: "Pilates",
    start: "April 4th, 12:15 pm",
    duration: "45 min",
    intensity: "Medium",
    location: "1917 Kings Way, Cleveland, Ohio",
    attendees: 2,
    maxsize: 8,
  },
  {
    name: "Shred Session 1.5",
    type: "RIPPED",
    start: "April 2nd, 8:00 pm",
    duration: "1.5 hrs",
    intensity: "High",
    location: "1st Chad Avenue, Scottsdale, Arizona",
    attendees: 4,
    maxsize: 20,
  },
];
